In [1]:
import importlib
import subprocess

import Advanced_SQL as asql
import duckdb
import SQL as sql

_ = importlib.reload(asql)
_ = importlib.reload(sql)

Use this cell to test any sql queries. This can be done in one of the following ways:

1. Fill in the `qry` within the """ """.
2. Call the question functions that you have already filled in from the SQL.py and Advanced_SQL.py files. An example of question_1 being called from the SQL.py file is currently commented out.

This cell can be copied if you wish to run multiple queries.

In [2]:
#qry = """  
#SELECT * FROM customers
#"""

qry = sql.question_1()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

        Name   Surname  CustomerID
0    grayson     aziza           9
1    grayson     aziza           9
2       aria     malek          14
3       aria     malek          14
4      henry     noemi          98
5      henry     noemi          98
6      alina    carter         160
7      alina    carter         160
8   scarlett     naomi         176
9   scarlett     naomi         176
10  gabriela     jesse         281
11  gabriela     jesse         281
12   juliana    hunter         304
13   juliana    hunter         304
14     chavy   rebecca         370
15     chavy   rebecca         370
16    nelson     rehan         501
17    nelson     rehan         501
18    eileen  augustus         630
19    eileen  augustus         630
20    wesley    shimon         687
21    wesley    shimon         687
22     aayan     devin         888
23     aayan     devin         888
24    alexis     amira         957
25    alexis     amira         957
26   crystal      luna         999
27   crystal      luna         999

In [3]:
#qry = """  
#SELECT * FROM customers
#"""

qry = sql.question_2()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

        Name   Surname  Income
0      caden     eshal   89820
1      sadie  victoria   89647
2     amelia  theodore   89641
3     samuel    hailey   89623
4     sydney    alyssa   89603
..       ...       ...     ...
490   stella      noel   40999
491    amber    yadiel   40771
492   matias    reuben   40529
493  eliezer   richard   40513
494  cynthia     faith   40116

[495 rows x 3 columns]

In [4]:
#qry = """  
#SELECT * FROM customers
#"""

qry = sql.question_3()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

   LoanTerm  ApprovalPercentage
0        12               48.24
1        24               47.55
2        36               45.70
3        48               53.39
4        60               46.57

In [5]:
#qry = """  
#SELECT * FROM customers
#"""

qry = sql.question_4()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

  CustomerClass  Count
0             B    521
1            A+      6
2             A    487

In [6]:
#qry = """  
#SELECT * FROM customers
#"""

qry = sql.question_5()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

   Count
0    275

In [7]:
qry = """
    SELECT CustomerClass,
    COUNT(CustomerID) AS Count
    FROM credit
    GROUP BY CustomerClass"""

# qry = sql.question_1()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

  CustomerClass  Count
0             B    246
1             C    275
2            A+      6
3             A    487

In [8]:
load_script_path = "database/database_load.py"
subprocess.run(["python3", load_script_path])

CompletedProcess(args=['python3', 'database/database_load.py'], returncode=0)

In [9]:
qry = asql.question_1()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

  CustomerClass  Avg_Income
0             B    64805.40
1            A+    76921.00
2             A    64263.17

In [10]:
qry = asql.question_2()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

  Region  RejectedApplications
0     NC                    62
1     WC                    58
2     EC                    68
3     GT                    65
4     LP                    61
5     FS                    51
6     MP                    67
7     NW                    50
8    KZN                    51

In [11]:


qry = asql.question_3()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

   Count
0   1000

In [12]:
qry = asql.question_4()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

   Count
0  12000

You are here

In [13]:
qry = asql.question_5()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

,CustomerID,JanuaryRepayments,JanuaryTotal,FebruaryRepayments,FebruaryTotal,MarchRepayments,MarchTotal,AprilRepayments,AprilTotal,MayRepayments,...,SeptemberRepayments,SeptemberTotal,OctoberRepayments,OctoberTotal,NovemberRepayments,NovemberTotal,DecemberRepayments,DecemberTotal,TotalRepayments,TotalAmount
0,1,0,0.0,0,0.0,0,0.0,1,479.0,0,...,0,0.0,0,0.0,0,0.0,0,0.0,2,930.0
1,2,1,359.0,0,0.0,1,352.0,0,0.0,0,...,0,0.0,0,0.0,0,0.0,1,58.0,3,769.0
2,3,2,413.0,0,0.0,1,154.0,0,0.0,0,...,0,0.0,0,0.0,0,0.0,0,0.0,4,638.0
3,4,0,0.0,0,0.0,0,0.0,0,0.0,0,...,1,123.0,0,0.0,0,0.0,0,0.0,1,123.0
4,5,0,0.0,0,0.0,0,0.0,1,468.0,0,...,0,0.0,0,0.0,0,0.0,0,0.0,1,468.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,0,0.0,0,0.0,0,0.0,0,0.0,0,...,0,0.0,0,0.0,0,0.0,0,0.0,1,496.0
996,997,0,0.0,0,0.0,0,0.0,0,0.0,0,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
997,998,0,0.0,0,0.0,0,0.0,0,0.0,0,...,1,294.0,0,0.0,1,133.0,0,0.0,2,427.0
998,999,0,0.0,0,0.0,0,0.0,0,0.0,0,...,1,95.0,0,0.0,0,0.0,0,0.0,1,95.0
999,1000,1,301.0,0,0.0,0,0.0,0,0.0,0,...,0,0.0,0,0.0,0,0.0,0,0.0,2,743.0

In [14]:
qry = asql.question_6()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

     CustomerID  Age  CorrectedAge  Gender
0             1   24            52  Female
1             2   34            71  Female
2             3   48            24  Female
3             4   34            34  Female
4             5   67            48  Female
..          ...  ...           ...     ...
995         996   39            77  Female
996         997   65            41  Female
997         998   52            39  Female
998         999   71            65  Female
999        1000   51            44    Male

[1000 rows x 4 columns]

In [15]:
qry = asql.question_7()


with duckdb.connect("database/loan.db") as cursor:
    result_set = cursor.execute(qry).df()

result_set

     CustomerID  Age  CorrectedAge  Gender  AgeCategory  Rank
0             1   24            52  Female        Adult     8
1             2   34            71  Female    Pensioner     8
2             3   48            24  Female  Young Adult     3
3             4   34            34  Female        Adult     8
4             5   67            48  Female        Adult    10
..          ...  ...           ...     ...          ...   ...
995         996   39            77  Female    Pensioner     8
996         997   65            41  Female        Adult    11
997         998   52            39  Female        Adult    10
998         999   71            65  Female    Pensioner     9
999        1000   51            44    Male        Adult     6

[1000 rows x 6 columns]

Should you break/incorrectly update any database tables, the database can be reset by running the following cell

In [16]:
load_script_path = "database/database_load.py"
subprocess.run(["python3", load_script_path])

CompletedProcess(args=['python3', 'database/database_load.py'], returncode=0)